### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by cloudscape-germany** [nice-table/bitmex-scaled-orders#28]
Getting this, please help, I am on MacOS.

```
[start] Node.js v18.13.0
[start] npm run start exited with code 1
[start] npm run start restarted
[start]
[start] > bmex-orderer@0.8.1 start
[start] > react-scripts start
[start]
[start] (node:56033) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
[start] (Use `node --trace-deprecation ...` to show where the warning was created)
[start] Starting the development server...
[start]
[start] Error: error:0308010C:digital envelope routines::unsupported
[start]     at new Hash (node:internal/crypto/hash:71:19)
[start]     at Object.createHash (node:crypto:133:10)
[start]     at module.exports (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/webpack/lib/util/createHash.js:90:53)
[start]     at NormalModule._initBuildHash (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/webpack/lib/NormalModule.js:401:16)
[start]     at handleParseError (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/webpack/lib/NormalModule.js:449:10)
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/webpack/lib/NormalModule.js:481:5
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/webpack/lib/NormalModule.js:342:12
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[start]     at iterateNormalLoaders (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[start]     at iterateNormalLoaders (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[start]     at runSyncOrAsync (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
[start]     at iterateNormalLoaders (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
[start]     at Array.<anonymous> (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[start]     at Storage.finished (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
[start] /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/react-scripts/scripts/start.js:19
[start]   throw err;
[start]   ^
[start]
[start] Error: error:0308010C:digital envelope routines::unsupported
[start]     at new Hash (node:internal/crypto/hash:71:19)
[start]     at Object.createHash (node:crypto:133:10)
[start]     at module.exports (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/webpack/lib/util/createHash.js:90:53)
[start]     at NormalModule._initBuildHash (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/webpack/lib/NormalModule.js:401:16)
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/webpack/lib/NormalModule.js:433:10
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/webpack/lib/NormalModule.js:308:13
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[start]     at context.callback (/Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[start]     at /Users/salvorhardin/dev/bitmex-scaled-orders/node_modules/babel-loader/lib/index.js:51:103 {
[start]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[start]   library: 'digital envelope routines',
[start]   reason: 'unsupported',
[start]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[start] }
[start]
[start] Node.js v18.13.0
[start] npm run start exited with code 1
```

**Comment by cloudscape-germany** [comment]
Solution worked on latest MacOS Sonoma 14.5

`export NODE_OPTIONS=--openssl-legacy-provider`
